#!/bin/bash

print_help() {
    echo "usage: $0 [info|add|search|del|provides|owns|sync|update|list] <string>"
    exit
}

check_arguments() {
    # These options require $2.
    if test "$1" = "add" -o \
            "$1" = "search" -o \
            "$1" = "del" -o \
            "$1" = "provides" -o \
            "$1" = "list" -o \
            "$1" = "info" -o \
            "$1" = "owns"; then

        # I have no idea why I cannot consolidate this. I should be able to.
        if test -n "$2"; then 
            return
        fi
    fi

    # These options doesn't take a $2.
    if test "$1" = "sync" -o \
            "$1" = "update"; then
        if test -z "$2"; then
            return
        fi
    fi

    # Either user passed $2 when he shouldn't have, didn't pass $2
    # when he should have, or provided an action which isn't available.
    print_help

}

couldnt() {
    echo "Couldn't find a way to '$1'.";
    exit
}

target() {
    echo -n "PKGMAN_"
    echo -n $1 | tr "abcdefghijklmnopqrstuvxyz" "ABCDEFGHIJKLMNOPQRSTUVXYZ"
}

main() {
    check_arguments $@
    CMD_TARGET=$1
    TARGET=$(target $1)

    shift 1

    PKGMAN_INFO=""
    PKGMAN_ADD=""
    PKGMAN_SEARCH=""
    PKGMAN_DEL=""
    PKGMAN_PROVIDES=""
    PKGMAN_OWNS=""
    PKGMAN_SYNC=""
    PKGMAN_UPDATE=""
    PKGMAN_LIST=""

    if test -x /usr/bin/apt-get; then
        PKGMAN_ADD="/usr/bin/apt-get install $@"
        PKGMAN_DEL="/usr/bin/apt-get remove $@"
        PKGMAN_SYNC="/usr/bin/apt-get update $@"
        PKGMAN_UPDATE="/usr/bin/apt-get upgrade $@"
    fi

    if test -x /usr/bin/apt-cache; then
        PKGMAN_SEARCH="/usr/bin/apt-cache search --names-only $@"
        PKGMAN_INFO="/usr/bin/apt-cache showpkg $@"
    fi

    if test -x /usr/bin/dpkg-query; then
        PKGMAN_LIST="/usr/bin/dpkg-query -L $@"
    fi

    if test -x /usr/bin/pacman; then
        PKGMAN_ADD="/usr/bin/pacman -S $@"
        PKGMAN_SEARCH="/usr/bin/pacman -Ss $@"
        PKGMAN_DEL="/usr/bin/pacman -Rsu $@"
        PKGMAN_OWNS="/usr/bin/pacman -Qo $@"
        PKGMAN_SYNC="/usr/bin/pacman -Sy"
        PKGMAN_UPDATE="/usr/bin/pacman -Su"
        PKGMAN_LIST="/usr/bin/pacman -Ql $@"
    fi

    if test -x /usr/bin/pacman-color; then
        PKGMAN_ADD="/usr/bin/pacman-color -S $@"
        PKGMAN_SEARCH="/usr/bin/pacman-color -Ss $@"
        PKGMAN_DEL="/usr/bin/pacman-color -Rsu $@"
        PKGMAN_OWNS="/usr/bin/pacman-color -Qo $@"
        PKGMAN_SYNC="/usr/bin/pacman-color -Sy"
        PKGMAN_UPDATE="/usr/bin/pacman-color -Su"
        PKGMAN_LIST="/usr/bin/pacman-color -Ql $@"
    fi

    if test -x /usr/bin/packer; then
        PKGMAN_ADD="/usr/bin/packer -S $@"
        PKGMAN_SEARCH="/usr/bin/packer -Ss $@"
        PKGMAN_UPDATE="/usr/bin/packer -Syu"
    fi

    if test -x /usr/bin/apt-file; then
        PKGMAN_PROVIDES="/usr/bin/apt-file search $@"
    fi

    if test -x /usr/bin/pkgfile; then
        PKGMAN_PROVIDES="/usr/bin/pkgfile $@"
    fi

    if test -n "${!TARGET}"; then
        ${!TARGET}
        return
    else
        couldnt $CMD_TARGET
    fi

}

main $@
